iterations: 500
position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: 500
feature_lr: 0.0025
opacity_lr: 0.025
scaling_lr: 0.005
rotation_lr: 0.001
exposure_lr_init: 0.01
exposure_lr_final: 0.001
exposure_lr_delay_steps: 0
exposure_lr_delay_mult: 0.0
percent_dense: 0.01
lambda_dssim: 0.2
densification_interval: 50
opacity_reset_interval: 1000
densify_from_iter: 100
densify_until_iter: 500
densify_grad_threshold: 0.0002
min_opacity_prune_threshold: 0.005
depth_l1_weight_init: 1.0
depth_l1_weight_final: 0.1
sparse_depth_weight_init: 0.0
sparse_depth_weight_final: 0.0
sparse_depth_max_points: 512
sparse_depth_global_max_points: 20000
sparse_depth_min_depth: 0.2
sparse_depth_require_rendered: true
random_background: false
optimizer_type: default
optimizer_beta1: 0.9
optimizer_beta2: 0.999
softmax_depth_beta: 5.0

debug_from: 0
detect_anomaly: true
quiet: false
start_checkpoint: null
testing_iterations: [100, 500]
save_iterations: [100, 500]
checkpoint_iterations: [100, 500]
